#region References

using System.Runtime.InteropServices;

#endregion

namespace Speedy.Automation.Internal.Inputs
{
	/// <summary>
	/// The HardwareInput structure contains information about a simulated message generated by an input device other than a keyboard or mouse.
	/// </summary>
	[StructLayout(LayoutKind.Sequential)]
	public struct HardwareInput
	{
		/// <summary>
		/// Value specifying the message generated by the input hardware.
		/// </summary>
		public uint Msg;

		/// <summary>
		/// Specifies the low-order word of the lParam parameter for uMsg.
		/// </summary>
		public ushort ParamL;

		/// <summary>
		/// Specifies the high-order word of the lParam parameter for uMsg.
		/// </summary>
		public ushort ParamH;
	}
}